# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.kuflow: DEBUG

spring:
  application:
    name: KuFlow Engine Worker Sample Email
  config:
    import:
      - "classpath:config/application-fillme.yaml"
      - "optional:classpath:config/application-local.yaml"
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: detect

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false

  mail:
    host: 127.0.0.1
    port: 3025
    username: username
    password: password
    test-connection: true

feign:
  autoconfiguration:
    jackson:
      enabled: true

application:
  temporal:

    # NOTE that the endpoint is the KUFLOW LIVE environment for
    # the KUFLOW GRPC TEMPORAL API.
    target: engine.kuflow.com:443
